### PR TITLE
Issue#289 Mounted file issue fix part-2

### PR DESCRIPTION
**Pull request by vkadi**
Signed-off-by: vkadi <kadiyan.vandana@gmail.com>

### CODE REVIEW

**Review by Cryptophobia — APPROVED** [review]
lgtm!

**Comment by Cryptophobia** [comment]
@desponda  @slimm609 @javiercri ,

This is good simple fix and will fix problems with v1.16.1 and reverts the code that has to be reverted here: https://github.com/vmware/kube-fluentd-operator/pull/293/files#diff-02dff57051ef7647011ad2da41c65fc9600bed4d6e4178bb85fd47d0c0c98509R263-R279 . Please merge when you can and close #289 .

Fixes and closes: https://github.com/vmware/kube-fluentd-operator/issues/289
Reverts non-scalable code in big clusters: https://github.com/vmware/kube-fluentd-operator/pull/293

**Comment by javiercri** [comment]
@vkadi lint is failing. Could you fix this one?

**Review by javiercri — APPROVED** [review]

**Comment by javiercri** [comment]
LGTM! 
Thanks for the PR!

**Comment by vkadi** [comment]
@javiercri Wondering, if we need to create a new tag to have these changes in v1.16.3 ? Or if I pull latest v1.16.2 I will have this fix in that, since its merged in master? Can you please share how are release planned for this project...

**Comment by javiercri** [comment]
@vkadi Ey, yeah we need to create a new tag. Let me finish some issues, i think i will generate a new release next week. Sorry for the delay

**Comment by vkadi** [comment]
@Cryptophobia @javiercri I am observing the boot time for fluentd container has increased(double the time) in v1.16.3,  Is this expected? 
Also, is there any slack/telegram channel where we can reach out with these generic question or support?

**Pull request merged**
