### PR TITLE
Efficient Kubernetes API Updates using Informers

### PR DESCRIPTION
**Pull request by rjackson90**
We noticed our AWS bill was higher than expected over a month ago, and when we looked into it we saw that the config reloader was making a lot of requests to our Kubernetes API server. These requests were causing a lot of cross-AZ traffic, both on their own and from our api servers to our etcd nodes in different AZes. Turning down the update frequency for the config reloader from 5s to 10m ameliorated the immediate monetary problem, at the cost of introducing significant lag in our config updates.

I took a look at the source code for the config reloader, and saw that there was an opportunity to significantly reduce the number of requests being made to the Kubernetes API server by making use of Informers, a facility shipped with the Kubernetes Go client SDK to efficiently track updates to API resources. I've been running this updated implementation in our production kubernetes cluster for several weeks and it's been working really well. There was an immediate reduction in API request volume from the config reloader as soon as I switched over to our fork. We were able to turn back up the update interval to 5 seconds with no impact on the number of requests being made of the kubernetes API server. We don't have very many compute nodes, 20-30 at any given time, but I imagine this would be a pretty serious scalability issue for larger clusters or other people like us who are running on AWS and have to worry about the costs of cross-AZ traffic between HA cluster components. 

I've left more detailed explanations of the "why" and "how" in my commit messages and as comments in the source. I've been running this fork for a few weeks and it's been well behaved, **however** we only ever used the `MultiMap` datasource so I can't really vouch for compatibility with the behavior of the default kubernetes datasource. I don't think it would be difficult to make this new datasource compatible enough with both existing datasources that they could be removed entirely. Indeed, one of my commits does precisely that, but I'm open to leaving them in if there are incompatibilities discovered in the new datasource.

### CODE REVIEW

**Comment by rjackson90** [comment]
Hi @jvassev do you have any questions about this proposed change that I can answer? Is there anything I can do to make review easier?

**Comment by jvassev** [comment]
Hi @rjackson90, this looks like a great improvement! Since you've tested mainly against the multimap datasource, don't you think it is safer to just change how the multimap is handled and leave the default datasource path untouched?

**Comment by jvassev** [comment]
On second thought, let's merge it as is because it is definitely a huge improvement. Thanks for making it happen! 
If there is a regression the revert for the default datasource would be trivial.

**Comment by rjackson90** [comment]
I'm happy to help, if any problems come up an immediate revert is wise. I was torn on whether or not to submit the PR with the default datasource modified, but landed in roughly the same place you did where it seemed sub-optimal for users to experience significantly different API call efficiency based on whether they selected a relatively minor configuration change.

**Pull request merged**
