### PR TITLE
Adds support for SA annotations

### PR DESCRIPTION
**Pull request by kkapoor1987**
Solves #160, #139 

Signed-off-by: Karan Kapoor <karan.kapoor@pega.com>

### CODE REVIEW

**Comment by kkapoor1987** [comment]
@dimalbaby  Can you please review this !!!

**Comment by kkapoor1987** [comment]
@viveksyngh Can you review and help me merge these changes

**Comment by viveksyngh** [comment]
@kkapoor1987 could you please rebase and update your branch with master ?

**Comment by kkapoor1987** [comment]
@viveksyngh thanks for the update... I believe it's ready for review now

**Review by viveksyngh — APPROVED** [review]
LGTM

**Review by Cryptophobia — CHANGES_REQUESTED** [review]
@kkapoor1987 , thank you for the contribution!

Do we need to update the chart version here? 

Just increment here by the minor version for some of users who could be using helm charts servers still:
https://github.com/vmware/kube-fluentd-operator/blob/master/charts/log-router/Chart.yaml#L7

**Comment by kkapoor1987** [comment]
@Cryptophobia  Thanks for that ...I just pushed it.

**Review by Cryptophobia — APPROVED** [review]
lgtm

**Pull request merged**
