### PR TITLE
Add support for CRI-O format

### PR DESCRIPTION
**Pull request by jonasrutishauser**
Support container logs from nodes running with docker or with crio (https://cri-o.io/).

### CODE REVIEW

**Comment by jvassev** [comment]
Hi @jonasrosland, I have not environment with cri-o to test this. Is your change compatible with docker AND crio? Would Docker container logs still be processed correctly?

**Comment by jonasrutishauser** [comment]
Yes it is compatible with docker and cri-o. The docker container logs should still be parsed the same way.

The multiline parser contains 2 patterns which are tried one after the other:
- The first will match all cri-o logs and parse the corresponding fields
https://github.com/vmware/kube-fluentd-operator/blob/d79805d8c56bf49e67034a99387b36b063390e98/config-reloader/templates/kubernetes.conf#L13-L15
- The second matches all json (docker) logs without parsing the json
https://github.com/vmware/kube-fluentd-operator/blob/d79805d8c56bf49e67034a99387b36b063390e98/config-reloader/templates/kubernetes.conf#L16-L17

The next filter is only for cri-o logs and it will concatenate all partials.
https://github.com/vmware/kube-fluentd-operator/blob/d79805d8c56bf49e67034a99387b36b063390e98/config-reloader/templates/kubernetes.conf#L23-L31

Then there is a filter which parses the json of docker logs.
https://github.com/vmware/kube-fluentd-operator/blob/d79805d8c56bf49e67034a99387b36b063390e98/config-reloader/templates/kubernetes.conf#L34-L44

The only small issue with this solution is in cri-o logs.
If the log line is a json object it will be parsed too.

**Comment by jonasrutishauser** [comment]
I have tested with the following input:
```
2016-10-06T00:17:09.669794202Z stdout F The content of the log entry 1
{"log":"Log line is here\n","stream":"stdout","time":"2019-01-01T11:11:11.111111111Z"}
2016-10-06T00:17:09.669794202Z stderr P First line of log entry 2
2016-10-06T00:17:09.669794202Z stderr P Second line of the log entry 2
2016-10-06T00:17:10.113242941Z stderr F Last line of the log entry 2
2016-10-06T00:18:12.123456743Z stdout F {"foo":"some","bar":"other"}
```
The output just after the second filter was the following:
```
2016-10-06 00:17:09.669794202 +0000 kubernetes.var.log.containers.container.log: {"stream":"stdout","log":"The content of the log entry 1"}
2019-01-01 11:11:11.111111111 +0000 kubernetes.var.log.containers.container.log: {"log":"Log line is here\n","stream":"stdout"}
2016-10-06 00:17:10.113242941 +0000 kubernetes.var.log.containers.container.log: {"stream":"stderr","log":"First line of log entry 2Second line of the log entry 2Last line of the log entry 2"}
2016-10-06 00:18:12.123456743 +0000 kubernetes.var.log.containers.container.log: {"stream":"stdout","log":"{\"foo\":\"some\",\"bar\":\"other\"}"}
```

**Comment by jvassev** [comment]
Thank you for your PR!

**Pull request merged**
